version: "3.8"

services:
  # Install postgres and setup the order database.
  postgres_order:
    container_name: postgres_ecommercedb_order
    image: debezium/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ecommercedb
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=ecommerce_password
  # Install postgres and setup the shipment database.
  postgres_shipment:
    container_name: postgres_ecommercedb_shipment
    image: debezium/postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=ecommercedb
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=ecommerce_password
