version: "3.8"

services:
  # Install postgres and setup the order database.
  postgres_order:
    container_name: postgres_ecommercedb_order
    image: debezium/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ecommercedb
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=ecommerce_password
  # Install postgres and setup the shipment database.
  postgres_shipment:
    container_name: postgres_ecommercedb_shipment
    image: debezium/postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=ecommercedb
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=ecommerce_password

  # Install zookeeper.
  zookeeper:
    image: debezium/zookeeper:1.2
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:1.2
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     # For local debugging of Main
     # - ADVERTISED_HOST_NAME=192.168.1.9
    depends_on:
      - zookeeper
  connect:
    image: debezium/connect:1.2
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
     - postgres_order
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_source_connect_configs
     - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
     - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
     - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
     - KAFKA_DEBUG=true
     - DEBUG_SUSPEND_FLAG=n
