## Server properties
server:
  port: 8080

## Database properties
spring:
  application:
    name: shipment_service
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml
    enabled: true
    default-schema: shipmentsch
  datasource:
    platform: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/ecommercedb?currentSchema=shipmentsch
    username: ecommerce_user
    password: ecommerce_password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

## Logging properties
logging:
  file:
    name: logs/shipment.log
  level:
    com:
      capitalone:
        auto:
          loans: INFO
    org:
      springframework:
        web: INFO

## Actuator config
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true


